name: pyqir-dev
channels:
- conda-forge
dependencies:
- maturin
- tox
- pip
- llvm=11
- llvm-tools=11
- llvmdev=11
- notebook
- matplotlib
- qutip
# Qiskit dependencies
- scipy>=1.0
- dill
- scikit-learn
- pip:
  - retworkx
  - qiskit=0.31
